export const headers = {
  v2: [
    "asset",
    "frozen",
    "paused",
    "can collateral",
    "LTV",
    "liquidation thereshold",
    "liquidation bonus",
    "reserve factor",
    "can borrow",
    "optimal utilization",
    "supply rate",
    "variable borrow rate",
    "can borrow stable",
    "stable borrow rate",
    "share of stable rate",
    "",
  ],
  v3: [
    "asset",
    "frozen",
    "paused",
    "can collateral",
    "LTV",
    "liquidation thereshold",
    "liquidation bonus",
    "reserve factor",
    "can borrow",
    "optimal utilization",
    "supply rate",
    "variable borrow rate",
    "can borrow stable",
    "stable borrow rate",
    "share of stable rate",
    "is isolated",
    "debt ceiling",
    "supply cap",
    "borrow cap",
    "emode LTV",
    "emode liq thereshold",
    "emode liq bonus",
    "borrowable in iso mode",
    "flashloan enabled",
    "",
  ],
  zerolend: [
    "asset",
    "frozen",
    "paused",
    "can collateral",
    "LTV",
    "liquidation thereshold",
    "liquidation bonus",
    "reserve factor",
    "can borrow",
    "optimal utilization",
    "variable borrow rate",
    "can borrow stable",
    "stable borrow rate",
    "share of stable rate",
    "is isolated",
    "debt ceiling",
    "supply cap",
    "borrow cap",
    "emode LTV",
    "emode liq thereshold",
    "emode liq bonus",
    "borrowable in iso mode",
    "flashloan enabled",
    "",
  ],
  benqi: [
    "asset",
    "collateral factor",
    "reserve factor",
    "close factor",
    "liquidation incentive",
  ],
  univ3: [],
  crvv2: [],
};
